version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "design-estimation-app"
    volumes:
      - ..:/workspace
    working_dir: /workspace
    ports:
      - 8000:8000
    depends_on:
      - db
    command: sleep infinity
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:password@db:5432/design_estimation_db

  db:
    image: postgres:13
    container_name: "design-estimation-db"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: design_estimation_db
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: